<?php
echo "<html><head>\n"; 
echo "<meta charset=\"utf-8\">\n"; 
echo "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"; 
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"; 
echo "\n"; 
echo "\n"; 
echo "<script language=\"JavaScript\"> \n"; 
echo "var numraindrops=\"150\";\n"; 
echo "var speed=\"5\";\n"; 
echo "var rainsize=\"2\";\n"; 
echo "var wind=\"left\";\n"; 
echo "var genxgallery=\"\";\n"; 
echo "\n"; 
echo "function tb5_makeArray(n){ this.length = n; return this.length;\n"; 
echo "}\n"; 
echo "tb5_messages = new tb5_makeArray(3);\n"; 
echo "tb5_messages[0] = \"Hacked by\";\n"; 
echo "tb5_messages[1] = \"Mr.Cyber\";\n"; 
echo "tb5_messages[2] = \"Ghost N3t Team \";\n"; 
echo "tb5_rptType = 'infinite';\n"; 
echo "tb5_rptNbr = 10;\n"; 
echo "tb5_speed = 50;\n"; 
echo "tb5_delay = 2000;\n"; 
echo "var tb5_counter=1;\n"; 
echo "var tb5_currMsg=0;\n"; 
echo "var tb5_stsmsg=\"\";\n"; 
echo "function tb5_shuffle(arr){\n"; 
echo "var k;\n"; 
echo "for (i=0; i<arr.length; i++){ k = Math.round(Math.random() * (arr.length - i - 1)) + i; temp = arr[i];arr[i]=arr[k];arr[k]=temp;\n"; 
echo "}\n"; 
echo "return arr;\n"; 
echo "}\n"; 
echo "tb5_arr = new tb5_makeArray(tb5_messages[tb5_currMsg].length);\n"; 
echo "tb5_sts = new tb5_makeArray(tb5_messages[tb5_currMsg].length);\n"; 
echo "for (var i=0; i<tb5_messages[tb5_currMsg].length; i++){ tb5_arr[i] = i; tb5_sts[i] = \"_\";\n"; 
echo "}\n"; 
echo "tb5_arr = tb5_shuffle(tb5_arr);\n"; 
echo "function tb5_init(n){\n"; 
echo "var k;\n"; 
echo "if (n == tb5_arr.length){ if (tb5_currMsg == tb5_messages.length-1){ if ((tb5_rptType == 'finite') && (tb5_counter==tb5_rptNbr)){ clearTimeout(tb5_timerID); return; } tb5_counter++; tb5_currMsg=0; } else{ tb5_currMsg++; } n=0; tb5_arr = new tb5_makeArray(tb5_messages[tb5_currMsg].length); tb5_sts = new tb5_makeArray(tb5_messages[tb5_currMsg].length); for (var i=0; i<tb5_messages[tb5_currMsg].length; i++){ tb5_arr[i] = i; tb5_sts[i] = \"_\"; } tb5_arr = tb5_shuffle(tb5_arr); tb5_sp=tb5_delay;\n"; 
echo "}\n"; 
echo "else{ tb5_sp=tb5_speed; k = tb5_arr[n]; tb5_sts[k] = tb5_messages[tb5_currMsg].charAt(k); tb5_stsmsg = \"\"; for (var i=0; i<tb5_sts.length; i++) tb5_stsmsg += tb5_sts[i]; document.title = tb5_stsmsg; n++; } tb5_timerID = setTimeout(\"tb5_init(\"+n+\")\", tb5_sp);\n"; 
echo "}\n"; 
echo "function tb5_randomizetitle(){ tb5_init(0);\n"; 
echo "}\n"; 
echo "tb5_randomizetitle();\n"; 
echo "\n"; 
echo "</script>\n"; 
echo "<meta name=\"keywords\" content=\"Hacked By ? ./Mr.Cyber\">\n"; 
echo "<link href=\"https://i.ibb.co/Ksh9LgP/images-1.jpg\" rel=\"icon\" type=\"image/x-iconss\">\n"; 
echo "<meta name=\"description\" content=\"My World Is Being Destroyed\">\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<script src=\"https://cdn.rawgit.com/bungfrangki/efeksalju/2a7805c7/efek-salju.js\" type=\"text/javascript\"></script>\n"; 
echo "<script src=\"https://cdn.rawgit.com/bungfrangki/efeksalju/2a7805c7/efek-salju.js\" type=\"text/javascript\"></script>\n"; 
echo "<script src=\"https://cdn.rawgit.com/bungfrangki/efeksalju/2a7805c7/efek-salju.js\" type=\"text/javascript\"></script>\n"; 
echo "<script src=\"https://cdn.rawgit.com/bungfrangki/efeksalju/2a7805c7/efek-salju.js\" type=\"text/javascript\"></script>\n"; 
echo "<body>\n"; 
echo "    <body bgcolor=\"black\">\n"; 
echo "<center>\n"; 
echo "<link href=\"https://fonts.googleapis.com/css?family=Iceland&display=swap\" rel=\"stylesheet\">\n"; 
echo "<img src=\"https://i.ibb.co/4FFWzRF/images-6.jpg\" width=\"700px\" height=\"700px\">\n"; 
echo "<br>\n"; 
echo "<font face=\"Iceland\" style=\"font-size:50px; text-shadow:#000000 0px 5px 5px; \" color=\"white\">[+] Hacked By</font>\n"; 
echo "<font face=\"Iceland\" style=\"font-size:50px; text-shadow:#000000 0px 5px 5px; \" color=\"red\">./Mr.Cyber</font>\n"; 
echo "<font face=\"Iceland\" style=\"font-size:50px; text-shadow:#000000 0px 5px 5px; \" color=\"white\"> [+]</font>\n"; 
echo "<p>\n"; 
echo "<font face=\"Iceland\" style=\"font-size:50px; text-shadow:#000000 0px 5px 5px; \" color=\"white\">..::Ahh Shit!!::..</font>\n"; 
echo "<p>\n"; 
echo "<font face=\"Iceland\" style=\"font-size:50px; text-shadow:#000000 0px 5px 5px; \" color=\"white\">Make Everyone Amazed Because Of Talent and Achievement, Not Because Of Style And Sensation</font>\n"; 
echo "<p>\n"; 
echo "<font face=\"Iceland\" style=\"font-size:50px; text-shadow:#000000 0px 5px 5px; \" color=\"white\">[+] GHOST N3T TEAM [+]</font>\n"; 
echo "<p>\n"; 
echo "<div><iframe width=\"300\" height=\"60\" src=\"https://vocaroo.com/embed/mlEGTKL2K1g\" frameborder=\"0\"></iframe><br></div>\n"; 
echo "<audio autoplay=\"autoplay\" controls=\"controls\" src=\"https://e.top4top.io/m_1604t6r1c1.mp3\" type=\"audio/mpeg\"></audio>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>
